
import { useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Upload, 
  File, 
  X, 
  Check, 
  AlertCircle 
} from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import { Progress } from "@/components/ui/progress";
import { DocumentFile, FileStatus } from "@/lib/types";
import { MAX_FILE_SIZE, SUPPORTED_FILE_TYPES } from "@/lib/constants";

interface FileUploaderProps {
  onFileProcessed: (file: DocumentFile) => void;
  language: string;
}

const FileUploader = ({ onFileProcessed, language }: FileUploaderProps) => {
  const [dragActive, setDragActive] = useState(false);
  const [files, setFiles] = useState<DocumentFile[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const validateFile = (file: File): string | null => {
    if (!SUPPORTED_FILE_TYPES.includes(file.type)) {
      return "File type not supported. Please upload a PDF or text document.";
    }
    
    if (file.size > MAX_FILE_SIZE) {
      return `File too large. Maximum size is ${MAX_FILE_SIZE / (1024 * 1024)}MB.`;
    }
    
    return null;
  };

  const handleFiles = (fileList: FileList | null) => {
    if (!fileList) return;
    
    const fileArray = Array.from(fileList);
    
    fileArray.forEach(file => {
      const error = validateFile(file);
      
      if (error) {
        toast({
          title: "Error",
          description: error,
          variant: "destructive",
        });
        return;
      }
      
      const newFile: DocumentFile = {
        id: crypto.randomUUID(),
        name: file.name,
        size: file.size,
        type: file.type,
        status: 'uploading',
        progress: 0,
        uploadDate: new Date(),
        language
      };
      
      setFiles(prev => [...prev, newFile]);
      
      // Simulate upload progress
      let progress = 0;
      const interval = setInterval(() => {
        progress += Math.random() * 10;
        
        if (progress >= 100) {
          clearInterval(interval);
          progress = 100;
          
          // Simulate processing
          setFiles(prev => 
            prev.map(f => 
              f.id === newFile.id 
                ? { ...f, status: 'processing' as FileStatus, progress: 100 } 
                : f
            )
          );
          
          // Simulate completion after processing
          setTimeout(() => {
            const processedFile = {
              ...newFile,
              status: 'completed' as FileStatus,
              progress: 100,
              summary: `This is a summary of ${file.name}. In a real implementation, this would be generated by an AI service based on the content of the document.`,
              url: URL.createObjectURL(file)
            };
            
            setFiles(prev => 
              prev.map(f => 
                f.id === newFile.id ? processedFile : f
              )
            );
            
            onFileProcessed(processedFile);
          }, 2000);
        } else {
          setFiles(prev => 
            prev.map(f => 
              f.id === newFile.id ? { ...f, progress } : f
            )
          );
        }
      }, 200);
    });
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    
    handleFiles(e.dataTransfer.files);
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    handleFiles(e.target.files);
  };

  const openFileSelector = () => {
    inputRef.current?.click();
  };

  const removeFile = (id: string) => {
    setFiles(prev => prev.filter(file => file.id !== id));
  };

  const getStatusIcon = (status: FileStatus) => {
    switch (status) {
      case 'uploading':
      case 'processing':
        return <div className="w-5 h-5 border-2 border-primary border-t-transparent rounded-full animate-spin" />;
      case 'completed':
        return <Check className="w-5 h-5 text-green-500" />;
      case 'error':
        return <AlertCircle className="w-5 h-5 text-destructive" />;
      default:
        return null;
    }
  };

  return (
    <section className="w-full max-w-3xl mx-auto px-4">
      <div
        className={`relative flex flex-col items-center justify-center w-full p-8 rounded-xl transition-all ${
          dragActive 
            ? "border-2 border-dashed border-primary bg-primary/5" 
            : "border-2 border-dashed border-muted glass"
        }`}
        onDragEnter={handleDrag}
        onDragOver={handleDrag}
        onDragLeave={handleDrag}
        onDrop={handleDrop}
      >
        <input
          ref={inputRef}
          type="file"
          className="hidden"
          multiple
          accept={SUPPORTED_FILE_TYPES.join(",")}
          onChange={handleChange}
        />
        
        <Upload className="w-12 h-12 text-primary mb-4" />
        
        <h3 className="text-xl font-semibold mb-2">
          Drag & drop your files
        </h3>
        
        <p className="text-muted-foreground text-center mb-4">
          Support for PDF, DOC, DOCX, and TXT files up to 10MB
        </p>
        
        <button
          className="btn-secondary"
          onClick={openFileSelector}
        >
          Select Files
        </button>
      </div>
      
      <AnimatePresence>
        {files.length > 0 && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="mt-8"
          >
            <h3 className="text-lg font-medium mb-4">Uploaded Files</h3>
            
            <div className="space-y-4">
              {files.map(file => (
                <motion.div
                  key={file.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, x: -10 }}
                  className="flex items-center p-4 rounded-lg glass"
                >
                  <div className="flex-shrink-0 mr-4">
                    <File className="w-8 h-8 text-primary" />
                  </div>
                  
                  <div className="flex-grow">
                    <div className="flex justify-between items-start">
                      <div>
                        <h4 className="font-medium truncate" style={{ maxWidth: "200px" }}>
                          {file.name}
                        </h4>
                        <p className="text-xs text-muted-foreground">
                          {(file.size / 1024).toFixed(1)} KB
                        </p>
                      </div>
                      <div className="flex items-center space-x-2">
                        {getStatusIcon(file.status)}
                        <button
                          onClick={() => removeFile(file.id)}
                          className="text-muted-foreground hover:text-destructive transition-colors"
                        >
                          <X className="w-5 h-5" />
                        </button>
                      </div>
                    </div>
                    
                    {(file.status === 'uploading' || file.status === 'processing') && (
                      <div className="mt-2">
                        <Progress value={file.progress} className="h-1" />
                        <p className="text-xs text-muted-foreground mt-1">
                          {file.status === 'uploading' ? 'Uploading' : 'Processing'}... {Math.round(file.progress || 0)}%
                        </p>
                      </div>
                    )}
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
};

export default FileUploader;
